version: "3.9"
services:
  backend:
    build: ./backend/.
    env_file:
      - ./backend/.env
    ports:
      - "1337:3000"
  frontend:
    build: ./frontend/.
    # env_file:
    #   - ./frontend/.env
    ports:
      - "1338:8080"